/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;

import brisorapp_v2.pkg0.AccesoBD;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author ElRonas-Mobile
 */
public class Cliente_agg_sel extends javax.swing.JFrame {

    /**
     * Creates new form Cliente_agg_sel
     */
    public Cliente_agg_sel() {
        initComponents();
        this.getContentPane().setBackground(Color.GRAY);
    }
    private int opcion;

    public void setOpcion(int a) {
        this.opcion = a;
    }

    public void ListarClientes(String Sql) throws SQLException {
        ClienteCB.removeAllItems();                                   /*1.ta*/
        ArrayList<Integer> Cedula = new ArrayList<>();                /*2.ta*/
        ArrayList<String> NombreCompleto = new ArrayList<>();         /*3.ta*/
        DefaultListModel Modelo = new DefaultListModel();             /*4.ta*/
        AccesoBD BD = new AccesoBD();                                 /*5.ta*/
        BD.Establecer_conexion();                                     /*6.  */
        ResultSet RSE = BD.Consulta(Sql);                             /*7.ta*/
        while (RSE.next()) {                                          /*8.n*tc+tc*/
            Cedula.add(RSE.getInt(1));                                /*9.n*to*/
            NombreCompleto.add(RSE.getString(2) + " " + RSE.getString(3));/*10.n*to*/
        }
        for (int i = 0; i < Cedula.size(); i++) {                       /*11.n*tc+tc*/
            String anidar = "Cedula: " + Cedula.get(i) + "   Nombre:" + NombreCompleto.get(i);/*12.n*to*/
            Modelo.add(i, anidar);                                                            /*13.n*to*/
            ClienteCB.addItem(Integer.toString(Cedula.get(i)));/*14. */
        }
        LClientes.setModel(Modelo);/*15. */
        BD.CerrarBD(); /*16. */
    }

    /**
     * Peor tiempo esperado (Tp):
     *
     * 5ta+ 3n*(tc+2to)+tc+3n*(ta+tc+2to)+tc
     *
     * 5ta + 3ntc + 6nto + tc + 3nta + 3ntc + 6n*to + tc
     *
     * (5ta + 3nta) + (3ntc + 3ntc + tc + tc) + (6nto + 6n*to)
     *
     * 5ta + 3nta = 8ta 3ntc + 3ntc + tc + tc = 8ntc 6nto + 6nto = 12n*to
     *
     * TP= 8ta + 8ntc + 12nto//
     *
     * Mejor tiempo esperado (Tm):
     *
     * 5ta+ 3n*(tc+2to)+tc
     *
     * 5ta+3n⋅tc+3n⋅2to+tc
     *
     * (5ta+tc)+(3n⋅tc+6n⋅to)
     *
     * 5ta+tc=(5ta+tc)
     *
     * 3n⋅tc+6n⋅to=3n⋅(tc+2to)
     *
     * Tm=5ta+3n⋅(tc+2to)
     *
     * Tiempo promedio esperado (Tu): 
     * Tu = (Tm+Tp)/2*
     * Tu= (5ta+3n⋅(tc+2to)+8ta+8ntc + 12nto)/2
     *
     * Tu= 13ta+3n⋅(tc+2to)+8n⋅tc+12n⋅to/2
     *
     * Tu= 13ta+3n⋅tc+6n⋅to+8n⋅tc+12n⋅to/2
     *
     * Tu= 13ta+(3n⋅tc+8n⋅tc)+(6n⋅to+12n⋅to)/2
     *
     * Tu= 13ta+11n⋅tc+18n⋅to/2      *
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ClienteCB = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        LClientes = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        ICedula = new javax.swing.JTextField();
        Buscar = new javax.swing.JButton();
        Agregar = new javax.swing.JButton();
        Atras = new javax.swing.JButton();
        Siguiente = new javax.swing.JButton();
        Recargar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Cliente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 110, 30));

        getContentPane().add(ClienteCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 130, 30));

        jScrollPane2.setViewportView(LClientes);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 310, 110));

        jLabel4.setText("Buscar Cliente:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 20));
        getContentPane().add(ICedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 140, -1));

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        getContentPane().add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 90, -1));

        Agregar.setText("Nuevo");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });
        getContentPane().add(Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        Atras.setText("<-- Atras");
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });
        getContentPane().add(Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        Siguiente.setText("Siguiente");
        Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(Siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, -1, -1));

        Recargar.setText("Recargar");
        Recargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecargarActionPerformed(evt);
            }
        });
        getContentPane().add(Recargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));

        setSize(new java.awt.Dimension(360, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        try {
            ListarClientes("select * from tbl_Cliente where IDC = " + Integer.parseInt(ICedula.getText()) + ";");
        } catch (SQLException ex) {

        }
    }//GEN-LAST:event_BuscarActionPerformed

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        NuevoCliente NC = new NuevoCliente();
        NC.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_AgregarActionPerformed

    private void SiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteActionPerformed
        if (opcion == 1) {
            Nuevo_Pedido NP = new Nuevo_Pedido();
            try {
                AccesoBD BD = new AccesoBD();
                BD.Establecer_conexion();
                BD.actualizarBD("insert into tbl_pedido(Fecha, cliente) values(default, " + Integer.parseInt((String) ClienteCB.getSelectedItem()) + ");");
                NP.ListarMenu("select * from tbl_menu;");
                NP.CantidadCalculo();
                BD.CerrarBD();
            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(Pedidos_sel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }

            NP.setVisible(true);
            setVisible(false);
        }else if(opcion == 2){
            ConsultaPedidos CP = new ConsultaPedidos();
            CP.setVisible(true);
            try {
                CP.ListarPedidos(Integer.parseInt((String) ClienteCB.getSelectedItem()));
            } catch (SQLException ex) {
                Logger.getLogger(Cliente_agg_sel.class.getName()).log(Level.SEVERE, null, ex);
            }
            setVisible(false);
        }else if (opcion == 3){
            EliminarPedido EP = new EliminarPedido();
            EP.setVisible(true);
            try {
                EP.ListarPedidos(Integer.parseInt((String) ClienteCB.getSelectedItem()));
            } catch (SQLException ex) {
                Logger.getLogger(Cliente_agg_sel.class.getName()).log(Level.SEVERE, null, ex);
            }
            setVisible(false);
        }

    }//GEN-LAST:event_SiguienteActionPerformed

    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
        Pedidos_sel PS = new Pedidos_sel();
        PS.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_AtrasActionPerformed

    private void RecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecargarActionPerformed
        try {
            ListarClientes("select * from tbl_Cliente;");
        } catch (SQLException ex) {
            Logger.getLogger(Cliente_agg_sel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_RecargarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente_agg_sel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente_agg_sel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente_agg_sel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente_agg_sel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente_agg_sel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JButton Atras;
    private javax.swing.JButton Buscar;
    private javax.swing.JComboBox<String> ClienteCB;
    private javax.swing.JTextField ICedula;
    private javax.swing.JList<String> LClientes;
    private javax.swing.JButton Recargar;
    private javax.swing.JButton Siguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
