/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;

import brisorapp_v2.pkg0.AccesoBD;
import java.awt.Color;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author ElRonas-Mobile
 */
public class ConsultaPedidos extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaPedidos
     */
    public ConsultaPedidos() {
        initComponents();
        this.getContentPane().setBackground(Color.GRAY);
    }
    AccesoBD BD = new AccesoBD();

    public void ListarPedidos(int IDC) throws SQLException {
        BD.Establecer_conexion();/*1.to*/
        ArrayList<String> PEI = new ArrayList<>();/*2.ta*/
        DefaultListModel Modelo = new DefaultListModel();/*3.ta*/
        ResultSet RS = BD.Consulta("select*from tbl_menu_pedido, tbl_pedido, tbl_menu where cliente = "+IDC+" and IDP=pedido;");/*4.ta*/
        while (RS.next()) { /*5.n*tc+tc*/
            PEI.add(RS.getInt(1) + " / " + RS.getString(9) + " / " + RS.getDouble(10) + " / " + RS.getInt(3) + " / " + RS.getDouble(4)); /*6.to*/
        }
        for (int i = 0; i < PEI.size(); i++) { /*7.n*tc+tc*/
            Modelo.add(i, PEI.get(i));/*8.to*/
        }
        PedidosList.setModel(Modelo);/*9.to*/
        BD.CerrarBD();/*10.to*/
    }
    
    /*
    Tiempo mejor esperado: Tm
    3ta+n*(tc+to)+tc + n*(tc+to)+tc+2to
    3ta + n*(tc+to) + tc + n*(tc+to) + tc + 2to
    = (3ta + 2tc + 2to) + n*(tc+to) + n*(tc+to)
    = 3ta + 2tc + 2to + n*(tc+to) + n*(tc+to)
    = 3ta + 2tc + 2to + n*(2*(tc+to))
    Tm= 3ta + 2tc + 2to + 2n*(tc+to)
    
    */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Atras = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        PedidosList = new javax.swing.JList<>();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        Atras.setText("<-- Atras");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PedidosList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(PedidosList);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 620, 240));

        jButton3.setText("X");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Lista de Pedidos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 20));

        jLabel2.setText("Pedido  /  Nombre de Producto  /  PrecioUnitario  /  Cantidad  /  Pecio Total");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, 20));

        setSize(new java.awt.Dimension(641, 338));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Pedidos_sel PS = new Pedidos_sel();
        PS.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaPedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras;
    private javax.swing.JList<String> PedidosList;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
