/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;

import brisorapp_v2.pkg0.AccesoBD;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author ElRonas-Mobile
 */
public class EliminarProducto extends javax.swing.JFrame {

    /**
     * Creates new form EliminarProducto
     */
    public EliminarProducto() {
        initComponents();
        this.getContentPane().setBackground(Color.GRAY);
    }

    public void ListarMenu(String Sql) throws SQLException {
        MenuCB.removeAllItems();                                                /*1.ta*/
        ArrayList<Integer> IDM = new ArrayList<>();                             /*2.ta*/
        ArrayList<String> PrecioNomb = new ArrayList<>();                       /*3.ta*/
        DefaultListModel Modelo = new DefaultListModel();                       /*4.ta*/
        AccesoBD BD = new AccesoBD();                                           /*5.ta*/
        BD.Establecer_conexion();                                               /*6.ta*/
        ResultSet RSE = BD.Consulta(Sql);                                       /*7.to*n*/
        while (RSE.next()) {                                                    /*8.to*n*/
            IDM.add(RSE.getInt(1));                                             /*9.ta*n*/
            PrecioNomb.add(RSE.getString(2) + ": $" + RSE.getDouble(3));        /*10.ta*n*/
        }
        for (int i = 0; i < IDM.size(); i++) {                                  /*11.tc*n*/
            String anidar = "ID: " + IDM.get(i) + " " + PrecioNomb.get(i);      /*12.ta*n*/
            MenuCB.addItem(Integer.toString(IDM.get(i)));                       /*13.ta*n*/
            Modelo.add(i, anidar);                                              /*14.ta*n*/
        }
        LMenu.setModel(Modelo);                                                 /*15.ta*/
        BD.CerrarBD();                                                          /*16.ta*/
    }
    /*Mejor Tiempo Esperado (Tm):
        Tm = ta + ta + ta + ta + ta + ta + to + to + ta + ta + ta + ta + ta + ta + ta
        Tm = 8ta + 2to

    Peor Tiempo Esperado (Tp):
        Tp = ta + ta + ta + ta + ta + ta + to + to + ta + ta + ta + to + ta + to + ta
        Tp = 8ta + 3to

    Tiempo Promedio Esperado (Tu):
        Tu = (Tm + Tp) / 2
        Tu = (8ta + 2to + 8ta + 3to) / 2
        Tu = (16ta + 5to) / 2
        Tu = 8ta + (5/2)to*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        MenuCB = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        LMenu = new javax.swing.JList<>();
        Cambiar = new javax.swing.JButton();
        salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Seleccione el codigo del producto");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 250, 30));

        getContentPane().add(MenuCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 130, 30));

        jScrollPane3.setViewportView(LMenu);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 360, 110));

        Cambiar.setText("Eliminar");
        Cambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CambiarActionPerformed(evt);
            }
        });
        getContentPane().add(Cambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));

        salir.setText("X");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, -1, -1));

        setSize(new java.awt.Dimension(405, 254));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CambiarActionPerformed
        AccesoBD BD = new AccesoBD();
        try {
            BD.Establecer_conexion();
            BD.actualizarBD("delete from tbl_menu_pedido where menu=" + Integer.parseInt((String) MenuCB.getSelectedItem()) + ";");
            BD.actualizarBD("delete from tbl_menu where IDM=" + Integer.parseInt((String) MenuCB.getSelectedItem()) + ";");
            ListarMenu("select * from tbl_menu;");
            BD.CerrarBD();
        } catch (SQLException ex) {
            Logger.getLogger(EliminarProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CambiarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        ProductosSel PS = new ProductosSel();
        PS.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EliminarProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cambiar;
    private javax.swing.JList<String> LMenu;
    private javax.swing.JComboBox<String> MenuCB;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
