/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;

import brisorapp_v2.pkg0.*;
import java.awt.Color;

/**
 *
 * @author ElRonas-Mobile
 */
public class Ingreso_empleados extends javax.swing.JFrame {

    /**
     * Creates new form Ingreso_empleados
     */
    public Ingreso_empleados() {
        initComponents();
        this.getContentPane().setBackground(Color.GRAY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nomb1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nomb2 = new javax.swing.JTextField();
        Ape1 = new javax.swing.JTextField();
        ape2 = new javax.swing.JTextField();
        cedula = new javax.swing.JTextField();
        Atras = new javax.swing.JButton();
        Aceptar = new javax.swing.JButton();
        VolverPrin = new javax.swing.JButton();
        advertencia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Ingrese los datos del nuevo empleado");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel2.setText("Primer Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 110, 20));

        jLabel3.setText("Segundo Nombre:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 110, 20));

        jLabel4.setText("Apellido Paterno: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 100, 20));

        jLabel5.setText("Apellido Materno: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 120, 20));

        nomb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomb1ActionPerformed(evt);
            }
        });
        getContentPane().add(nomb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 140, -1));

        jLabel6.setText("Cedula: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, 20));
        getContentPane().add(nomb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 140, -1));
        getContentPane().add(Ape1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 140, -1));
        getContentPane().add(ape2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 140, -1));
        getContentPane().add(cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 140, -1));

        Atras.setText("<-- Atras");
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });
        getContentPane().add(Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });
        getContentPane().add(Aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));

        VolverPrin.setText("Volver al menu Principal");
        VolverPrin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverPrinActionPerformed(evt);
            }
        });
        getContentPane().add(VolverPrin, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, -1));
        getContentPane().add(advertencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 400, 20));

        setSize(new java.awt.Dimension(419, 321));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nomb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomb1ActionPerformed

    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
        Empleados_sel ES = new Empleados_sel();
        ES.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_AtrasActionPerformed

    private void VolverPrinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverPrinActionPerformed
        MenuPrin MP = new MenuPrin();
        MP.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_VolverPrinActionPerformed

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        try {
            int cedu = Integer.parseInt(cedula.getText());
            String nombre1 = nomb1.getText();
            String nombre2 = nomb2.getText();
            String apellido1 = Ape1.getText();
            String apellido2 = ape2.getText();
            Empleado Em = new Empleado(cedu, nombre1, nombre2, apellido1, apellido2);
            AccesoBD BD = new AccesoBD();
            BD.Establecer_conexion();
            BD.actualizarBD("insert into tbl_empleado(IDE, nombre1, nombre2, PApellido, Mapellido) values(" + Em.getCedula() + " ,'" + Em.getNombre1() + "', '" + Em.getNombre2() + "', '" + Em.getApellidoPaterno() + "', '" + Em.getApellidoMaterno() + "');");
            BD.CerrarBD();
            MenuPrin MP = new MenuPrin();
            MP.setVisible(true);
            setVisible(false);
        } catch (Exception e) {
            advertencia.setText("Error: Revise los datos ingresados");
        }
    }//GEN-LAST:event_AceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingreso_empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingreso_empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingreso_empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingreso_empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingreso_empleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JTextField Ape1;
    private javax.swing.JButton Atras;
    private javax.swing.JButton VolverPrin;
    private javax.swing.JLabel advertencia;
    private javax.swing.JTextField ape2;
    private javax.swing.JTextField cedula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nomb1;
    private javax.swing.JTextField nomb2;
    // End of variables declaration//GEN-END:variables
}
