/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;

import brisorapp_v2.pkg0.*;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ElRonas-Mobile
 */
public class NuevoCliente extends javax.swing.JFrame {

    /**
     * Creates new form NuevoCliente
     */
    public NuevoCliente() {
        initComponents();
        this.getContentPane().setBackground(Color.GRAY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ICliente = new javax.swing.JToggleButton();
        CNombre = new javax.swing.JTextField();
        CApellido = new javax.swing.JTextField();
        CCedula = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Ingrese los datos del nuevo cliente");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 30));

        jLabel3.setText("Apellido:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel4.setText("Cedula:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        ICliente.setText("Siguiente");
        ICliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IClienteActionPerformed(evt);
            }
        });
        getContentPane().add(ICliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, -1, -1));

        CNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CNombreActionPerformed(evt);
            }
        });
        getContentPane().add(CNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 190, -1));
        getContentPane().add(CApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 190, -1));
        getContentPane().add(CCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 190, -1));

        jButton1.setText("<--Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        setSize(new java.awt.Dimension(351, 204));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CNombreActionPerformed

    private void IClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IClienteActionPerformed
        try {
            AccesoBD BD = new AccesoBD();                                                         /*1.ta*/
            int cedu = Integer.parseInt(CCedula.getText());                                       /*2.ta*/
            String nomb = CNombre.getText();                                                      /*3.ta*/
            String apell = CApellido.getText();                                                   /*4.ta*/
            Cliente C = new Cliente(cedu, nomb, apell);                                           /*5.ta*/
            BD.Establecer_conexion();                                                             /*6.ta*/
            BD.actualizarBD("insert into tbl_Cliente(IDC, Nombre, Apellido) values(" +            /*7.to*/
                    C.getCedula() + " , '" + C.getNombre() + "', '" + C.getApellido() + "');");
            BD.CerrarBD();                                                                        /*8.ta*/
        } catch (SQLException ex) {                                                               /*9.ta*/
            Logger.getLogger(NuevoCliente.class.getName()).log(Level.SEVERE, null, ex);           
        }

        setVisible(false);                                                                        /*10.ta*/
        /*Mejor Tiempo Esperado (Tm):
            Tm = ta + ta + ta + ta + ta + ta + to + ta
            Tm = 7ta + to*/
        /*Peor Tiempo Esperado (Tp):
            Tp = ta + ta + ta + ta + ta + ta + to + ta + to
            Tp = 8ta + 2to*/
        /*Tiempo Promedio Esperado (Tu):
            Tu = (Tm + Tp) / 2
            Tu = (7ta + to + 8ta + 2to) / 2
            Tu = (15ta + 3to) / 2
            Tu = 7.5ta + 1.5to*/
    }//GEN-LAST:event_IClienteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Cliente_agg_sel CAS = new Cliente_agg_sel();
        CAS.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CApellido;
    private javax.swing.JTextField CCedula;
    private javax.swing.JTextField CNombre;
    private javax.swing.JToggleButton ICliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
